name: timezones_list
description: A comprehensive collection of UTC timezones, providing accurate and up-to-date information to help you manage time-related tasks and timezone conversions in your Dart application.
version: 0.0.6
homepage: https://github.com/arv-aks/timezones_list

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
